Step 1-Import Required Libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

Libraries imported successfully!

Step 2-Load the Scraped Dataset

In [4]:
from google.colab import files

uploaded = files.upload()
import pandas as pd

df = pd.read_csv("books_scraped.csv")

print("Dataset loaded successfully!")
display(df.head())

Saving books_scraped.csv to books_scraped (1).csv
Dataset loaded successfully!

                               Book Name  Price Rating
0                   A Light in the Attic  51.77  Three
1                     Tipping the Velvet  53.74    One
2                             Soumission  50.10    One
3                          Sharp Objects  47.82   Four
4  Sapiens: A Brief History of Humankind  54.23   Five

STEP 3 — Explore Dataset Structure

In [5]:
print("Dataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nFirst 5 Records:")
display(df.head())

Dataset Shape: (20, 3)

Column Names:
['Book Name', 'Price', 'Rating']

Data Types:
Book Name     object
Price        float64
Rating        object
dtype: object

First 5 Records:

                               Book Name  Price Rating
0                   A Light in the Attic  51.77  Three
1                     Tipping the Velvet  53.74    One
2                             Soumission  50.10    One
3                          Sharp Objects  47.82   Four
4  Sapiens: A Brief History of Humankind  54.23   Five

STEP 4: Check Missing Values

In [6]:
print("Missing Values in Each Column:")
print(df.isnull().sum())

print("\nTotal Missing Values:")
print(df.isnull().sum().sum())

Missing Values in Each Column:
Book Name    0
Price        0
Rating       0
dtype: int64

Total Missing Values:
0

STEP 5: Generate Descriptive Statistics

In [7]:
print("Descriptive Statistics:")

print("\nPrice Statistics:")
print(df["Price"].describe())

print("\nRating Statistics:")
print(df["Rating"].describe())

Descriptive Statistics:

Price Statistics:
count    20.000000
mean     38.048500
std      15.135231
min      13.990000
25%      22.637500
50%      41.380000
75%      51.865000
max      57.250000
Name: Price, dtype: float64

Rating Statistics:
count      20
unique      5
top       One
freq        6
Name: Rating, dtype: object

STEP 6: Ask Meaningful Questions

In [8]:
print("Meaningful Questions for EDA:")

questions = [
    "1. What is the average price of the books?",
    "2. What is the minimum and maximum book price?",
    "3. Which rating is most common among the books?",
    "4. Are higher-rated books generally more expensive?",
    "5. Are there any unusual or extreme book prices?"
]

for question in questions:
    print(question)

Meaningful Questions for EDA:
1. What is the average price of the books?
2. What is the minimum and maximum book price?
3. Which rating is most common among the books?
4. Are higher-rated books generally more expensive?
5. Are there any unusual or extreme book prices?

STEP 7: Analyze Trends and Patterns

In [9]:
print("TREND AND PATTERN ANALYSIS")

# Price analysis
print("\nPrice Analysis:")
print("Average Price:", round(df["Price"].mean(), 2))
print("Minimum Price:", df["Price"].min())
print("Maximum Price:", df["Price"].max())

# Rating pattern
print("\nRating Distribution:")
print(df["Rating"].value_counts())

# Most common rating
most_common_rating = df["Rating"].mode()[0]
print("\nMost Common Rating:", most_common_rating)

TREND AND PATTERN ANALYSIS

Price Analysis:
Average Price: 38.05
Minimum Price: 13.99
Maximum Price: 57.25

Rating Distribution:
Rating
One      6
Five     4
Four     4
Three    3
Two      3
Name: count, dtype: int64

Most Common Rating: One

STEP 8: Analyze Relationships

In [10]:
rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

df["Rating_Numeric"] = df["Rating"].map(rating_map)

print("Average Price by Rating:")
print(df.groupby("Rating_Numeric")["Price"].mean())

print("\nCorrelation between Price and Rating:")
print(df["Price"].corr(df["Rating_Numeric"]))

Average Price by Rating:
Rating_Numeric
1    40.018333
2    36.830000
3    42.316667
4    31.105000
5    39.750000
Name: Price, dtype: float64

Correlation between Price and Rating:
-0.07585689715186737

STEP 9: Detect Anomalies and Outliers

In [11]:
Q1 = df["Price"].quantile(0.25)
Q3 = df["Price"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = df[
    (df["Price"] < lower_limit) |
    (df["Price"] > upper_limit)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

print("\nLower Limit:", lower_limit)
print("Upper Limit:", upper_limit)

print("\nNumber of Outliers:", len(outliers))

print("\nOutlier Records:")
display(outliers)

Q1: 22.6375
Q3: 51.865
IQR: 29.227500000000003

Lower Limit: -21.203750000000003
Upper Limit: 95.70625000000001

Number of Outliers: 0

Outlier Records:

Empty DataFrame
Columns: [Book Name, Price, Rating, Rating_Numeric]
Index: []

STEP 10: Identify Data Issues

In [12]:
print("DATA QUALITY CHECK")

print("\nDuplicate Records:", df.duplicated().sum())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nData Types:")
print(df.dtypes)

print("\nRating Values:")
print(df["Rating"].unique())

print("\nPrice Range:")
print("Minimum Price:", df["Price"].min())
print("Maximum Price:", df["Price"].max())

DATA QUALITY CHECK

Duplicate Records: 0

Missing Values:
Book Name         0
Price             0
Rating            0
Rating_Numeric    0
dtype: int64

Data Types:
Book Name          object
Price             float64
Rating             object
Rating_Numeric      int64
dtype: object

Rating Values:
['Three' 'One' 'Four' 'Five' 'Two']

Price Range:
Minimum Price: 13.99
Maximum Price: 57.25

STEP 11: Summarize Key Insights

In [14]:
print("KEY INSIGHTS FROM EDA")
print("-" * 40)

print("1. The dataset contains", df.shape[0], "books.")
print("2. The dataset contains", df.shape[1], "columns.")
print("3. Missing values:", df.isnull().sum().sum())
print("4. Duplicate records:", df.duplicated().sum())
print("5. Average book price:", round(df["Price"].mean(), 2))
print("6. Minimum book price:", df["Price"].min())
print("7. Maximum book price:", df["Price"].max())
print("8. Most common rating:", df["Rating"].mode()[0])
print("9. Number of price outliers:", len(outliers))

KEY INSIGHTS FROM EDA
----------------------------------------
1. The dataset contains 20 books.
2. The dataset contains 4 columns.
3. Missing values: 0
4. Duplicate records: 0
5. Average book price: 38.05
6. Minimum book price: 13.99
7. Maximum book price: 57.25
8. Most common rating: One
9. Number of price outliers: 0

STEP 12: EDA Conclusion

In [15]:
print("EDA CONCLUSION")
print("-" * 40)

print("""
The Exploratory Data Analysis was performed on the scraped book dataset.

Key findings:
1. The dataset contains 20 books and 3 main columns.
2. No missing values were found in the dataset.
3. No duplicate records were found.
4. Book prices were analyzed using descriptive statistics.
5. Rating patterns were explored and converted into numerical values
   for relationship analysis.
6. The relationship between book price and rating was analyzed using correlation.
7. The dataset was checked for price outliers using the IQR method.
8. The analysis helped identify data patterns, relationships, and potential
   data quality issues for further analysis.

Overall, the EDA provided a clear understanding of the structure,
quality, trends, and relationships within the dataset.
""")

EDA CONCLUSION
----------------------------------------

The Exploratory Data Analysis was performed on the scraped book dataset.

Key findings:
1. The dataset contains 20 books and 3 main columns.
2. No missing values were found in the dataset.
3. No duplicate records were found.
4. Book prices were analyzed using descriptive statistics.
5. Rating patterns were explored and converted into numerical values
   for relationship analysis.
6. The relationship between book price and rating was analyzed using correlation.
7. The dataset was checked for price outliers using the IQR method.
8. The analysis helped identify data patterns, relationships, and potential
   data quality issues for further analysis.

Overall, the EDA provided a clear understanding of the structure,
quality, trends, and relationships within the dataset.